"""Round-7: every table fragment (paper/latex/tables/r7_*.tex) and every
result macro (paper/latex/numbers.tex) is generated from results/final_r7/.
No result number in the manuscript or supplement is hand-typed.

Usage: python scripts/make_tables_r7.py [master_dir]
"""
from __future__ import annotations

import os
import sys

import numpy as np
import pandas as pd

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
MC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "results", "final_r7")
TAB = os.path.join(ROOT, "paper", "latex", "tables")
NUM = os.path.join(ROOT, "paper", "latex", "numbers.tex")
os.makedirs(TAB, exist_ok=True)

PT, PTG, PTD = "PatchTST-SSL(HoW-cond)", "PatchTST-SSL(global-MAD)", "PatchTST-SSL(HoD-cond)"
HW, HWG, HWD = "HOW-profile(HoW-cond)", "HOW-profile(global-MAD)", "HOW-profile(HoD-cond)"
PM, TW, SL = "PatchTST-SSL(HoW-cond, patch-mask train)", "TOWT(HoW-cond)", "HOW-profile+z(slot)"
GEN = ["IsolationForest(t)", "OC-SVM(t)", "Autoencoder(t)", "LSTM-AE(t)"]
NICE = {PT: r"\textbf{PatchTST $+$ HoW scoring (ours)}", PTG: r"PatchTST $+$ global scoring",
        PTD: r"PatchTST $+$ HoD scoring", HW: r"HOW-residual $+$ HoW scoring",
        HWG: r"HOW-residual $+$ global scoring", HWD: r"HOW-residual $+$ HoD scoring",
        PM: r"PatchTST (40\% patch-mask training) $+$ HoW", TW: r"TOWT-residual $+$ HoW scoring",
        SL: r"slotwise HOW-$z$ baseline", "IsolationForest(t)": "Isolation Forest (tuned)",
        "OC-SVM(t)": "OC-SVM (tuned)", "Autoencoder(t)": "Dense autoencoder (tuned)",
        "LSTM-AE(t)": "LSTM autoencoder (tuned)"}
SHORT = {PT: r"\textbf{PatchTST (ours)}", HW: "HOW profile", TW: "TOWT"}
GROUPS = [("Factorial: backbone $\\times$ scoring", [PT, PTG, HW, HWG]),
          ("Calendar-granularity ablation", [PTD, HWD]),
          ("Other residual detectors", [TW, SL]),
          ("Generic detectors (own score, same flagger)", GEN),
          ("Masking ablation", [PM])]
TYPES = ("spike", "drift", "schedule")
SEVN = {1: "subtle", 2: "moderate", 3: "obvious"}
MACROS: dict[str, object] = {}


def M(name, v):
    MACROS[name] = v


def load(name):
    p = os.path.join(MC, name)
    return pd.read_csv(p) if os.path.exists(p) else None


def ms(x, dec=2, pct=False):
    x = np.asarray(x, float)
    x = x[~np.isnan(x)]
    k = 100 if pct else 1
    if len(x) == 0:
        return "---"
    if len(x) == 1:
        return f"{k * x[0]:.{dec}f}"
    return f"{k * x.mean():.{dec}f} $\\pm$ {k * x.std(ddof=1):.{dec}f}"


def pct(v, dec=1):
    return f"{100 * v:+.{dec}f}\\%"


def write(name, lines):
    open(os.path.join(TAB, name), "w").write(
        "%% AUTO-GENERATED by scripts/make_tables_r7.py -- do not edit\n" + "\n".join(lines) + "\n")


def per_seed(det, cols):
    return det.groupby(["model", "seed"])[cols].mean().reset_index()


# ------------------------------------------------------------- detection
def t_detection(det):
    ps = per_seed(det, ["precision", "recall", "f1", "range_precision", "range_recall",
                        "range_f1", "false_alarm_rate"])
    L = [r"\begin{tabular}{lccccccc}", r"\toprule",
         r" & \multicolumn{3}{c}{Event level} & \multicolumn{3}{c}{Range (overlap) level} & \\",
         r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}",
         r"Detector & P & R & F1 & P & R & F1 & NIAR (\%) \\", r"\midrule"]
    for gi, (gname, models) in enumerate(GROUPS):
        if gi:
            L.append(r"\midrule")
        L.append(rf"\multicolumn{{8}}{{l}}{{\emph{{{gname}}}}} \\")
        for m in models:
            g = ps[ps["model"] == m]
            if not len(g):
                continue
            L.append(f"{NICE[m]} & {ms(g['precision'])} & {ms(g['recall'])} & {ms(g['f1'], 3)} & "
                     f"{ms(g['range_precision'])} & {ms(g['range_recall'])} & {ms(g['range_f1'], 3)} & "
                     f"{ms(g['false_alarm_rate'], 2, pct=True)} \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("r7_detection.tex", L)
    for m, key in [(PT, "PT"), (PTG, "PTG"), (PTD, "PTD"), (HW, "HW"), (HWG, "HWG"), (HWD, "HWD"),
                   (PM, "PM"), (TW, "TW"), (SL, "SL"), ("IsolationForest(t)", "IF"),
                   ("OC-SVM(t)", "OCSVM"), ("Autoencoder(t)", "AE"), ("LSTM-AE(t)", "LSTMAE")]:
        g = ps[ps["model"] == m]
        if not len(g):
            continue
        for col, suf in [("f1", "F"), ("range_f1", "RF"), ("precision", "P"), ("recall", "R"),
                         ("false_alarm_rate", "NIAR"), ("range_recall", "RR")]:
            M(f"{key}{suf}", float(g[col].mean()))
        M(f"{key}Fsd", float(g["f1"].std(ddof=1)) if len(g) > 1 else 0.0)
    rr = ps[ps["model"].isin([PT, PTG, HW, HWG, PTD, HWD, TW, SL] + GEN)]["range_recall"]
    M("RangeRecallMin", float(ps.groupby("model")["range_recall"].mean().min()))
    M("RangeRecallMax", float(ps.groupby("model")["range_recall"].mean().max()))
    f = ps.groupby("model")["f1"].mean()
    M("FMinAll", float(f.min())); M("FMaxAll", float(f.max()))
    r = ps.groupby("model")["range_f1"].mean()
    M("RFMinAll", float(r.min())); M("RFMaxAll", float(r.max()))
    top = r.sort_values(ascending=False)
    M("FTopName", NICE[f.idxmax()].replace(r"\textbf{", "").replace("}", "").replace(" (ours)", ""))
    M("FTop", float(f.max()))
    M("RFTop", float(r.max()))
    M("RFTopNameB", NICE[r.idxmax()].replace(r"\textbf{", "").replace("}", "").replace(" (ours)", ""))
    M("RFTopName", NICE[top.index[0]].replace(r"\textbf{", "").replace("}", "") if top.index[0] != PT else "ours")
    M("NBuildings", int(det["building_id"].nunique()))
    M("NSites", int(det["building_id"].str.split("_").str[0].nunique()))
    M("NSiteMax", int(det.drop_duplicates("building_id")["building_id"].str.split("_").str[0].value_counts().max()))


# ------------------------------------------------------------- factorial
def t_factorial(fs):
    def cell(metric, m):
        r = fs[(fs["metric"] == metric) & (fs["family"] == "cell") & (fs["contrast"] == m)]
        return float(r["estimate"].iloc[0])
    L = [r"\begin{tabular}{lcccccccc}", r"\toprule",
         r"\multicolumn{9}{l}{\emph{(a) Cell means, building-level, seed-averaged (event F1 / range F1)}} \\",
         r"\midrule",
         r" & \multicolumn{2}{c}{Global scoring} & \multicolumn{2}{c}{HoW-conditional scoring} & & & & \\",
         r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
         r"Backbone & event & range & event & range & & & & \\", r"\midrule"]
    for lab, g, h in [("HOW profile", HWG, HW), ("PatchTST", PTG, PT)]:
        L.append(f"{lab} & {cell('f1', g):.3f} & {cell('range_f1', g):.3f} & "
                 f"{cell('f1', h):.3f} & {cell('range_f1', h):.3f} & & & & \\\\")
    L += [r"\midrule",
          r"\multicolumn{9}{l}{\emph{(b) Contrasts on event F1 (Holm within family); sensitivity analyses on the right}} \\",
          r"\midrule",
          r"Contrast & est. & 95\% CI & $p_t$ & Holm $p$ & $p_\mathrm{perm}$ & site-cluster 95\% CI & $p_\mathrm{mixed}$ & W/L \\",
          r"\midrule"]
    lab = {"backbone main effect": "Backbone main effect",
           "scoring main effect": "Scoring main effect",
           "interaction (scoring effect: PatchTST - HOW)": "Interaction",
           "PatchTST(HoW) - HOW(HoW)  [backbone | HoW]": "Backbone $\\mid$ HoW",
           "PatchTST(global) - HOW(global)  [backbone | global]": "Backbone $\\mid$ global",
           "PatchTST(HoW) - PatchTST(global)  [scoring | PatchTST]": "Scoring $\\mid$ PatchTST",
           "HOW(HoW) - HOW(global)  [scoring | HOW]": "Scoring $\\mid$ HOW"}
    ev = fs[fs["metric"] == "f1"]
    for fam in ("primary", "simple"):
        if fam == "simple":
            L.append(r"\midrule")
        for _, r in ev[ev["family"] == fam].iterrows():
            L.append(f"{lab[r['contrast']]} & {r['estimate']:+.3f} & [{r['ci95_lo']:+.3f}, {r['ci95_hi']:+.3f}] & "
                     f"{fmtp(r['p_t'])} & {fmtp(r['holm_p'])} & {fmtp(r['p_perm'])} & "
                     f"[{r['cluster_lo']:+.3f}, {r['cluster_hi']:+.3f}] & {fmtp(r['p_mixed'])} & "
                     f"{int(r['wins'])}/{int(r['losses'])} \\\\")
    t = ev[ev["family"] == "tost"].iloc[0]
    L += [r"\midrule",
          f"TOST, backbone $\\mid$ HoW ($\\pm$0.03) & {t['estimate']:+.3f} & 90\\%: [{t['ci90_lo']:+.3f}, {t['ci90_hi']:+.3f}] & "
          f"\\multicolumn{{6}}{{l}}{{$p_\\mathrm{{TOST}} = {t['p_tost']:.2f}$}} \\\\",
          r"\bottomrule", r"\end{tabular}"]
    write("r7_factorial.tex", L)
    for metric, pre in [("f1", ""), ("range_f1", "R"), ("false_alarm_rate", "N")]:
        d = fs[fs["metric"] == metric]
        for c, key in [("backbone main effect", "BBME"), ("scoring main effect", "SCME"),
                       ("interaction (scoring effect: PatchTST - HOW)", "INT"),
                       ("PatchTST(HoW) - HOW(HoW)  [backbone | HoW]", "BBHow"),
                       ("PatchTST(global) - HOW(global)  [backbone | global]", "BBGlob"),
                       ("PatchTST(HoW) - PatchTST(global)  [scoring | PatchTST]", "SCPT"),
                       ("HOW(HoW) - HOW(global)  [scoring | HOW]", "SCHW")]:
            r = d[d["contrast"] == c].iloc[0]
            for col, suf in [("estimate", ""), ("ci95_lo", "Lo"), ("ci95_hi", "Hi"), ("p_t", "P"),
                             ("holm_p", "Holm"), ("p_perm", "Perm"), ("cluster_lo", "CLo"),
                             ("cluster_hi", "CHi"), ("p_mixed", "Mixed")]:
                M(f"{pre}{key}{suf}", float(r[col]))
            M(f"{pre}{key}Wins", int(r["wins"])); M(f"{pre}{key}Losses", int(r["losses"]))
        t = d[d["family"] == "tost"].iloc[0]
        M(f"{pre}TOSTp", float(t["p_tost"])); M(f"{pre}TOSTLo", float(t["ci90_lo"]))
        M(f"{pre}TOSTHi", float(t["ci90_hi"]))
    M("PairedN", int(fs[(fs["metric"] == "f1") & (fs["family"] == "primary")]["n"].iloc[0]))


def fmtp(p):
    if pd.isna(p):
        return "---"
    if p < 1e-4:
        return r"$<10^{-4}$"
    if p >= 0.001:
        return f"{p:.3f}"
    m, e = f"{p:.1e}".split("e")
    return f"${m}\\times10^{{{int(e)}}}$"


# ------------------------------------------------------------- per type
def type_recall(evd, models):
    g = evd[evd["model"].isin(models)].groupby(["model", "seed", "type"])["detected"].mean()
    return g.groupby(["model", "type"]).agg(["mean", "std"])


def t_granularity(det, evd):
    ps = per_seed(det, ["precision", "recall", "f1", "false_alarm_rate"])
    tr = type_recall(evd, [PT, PTD, PTG, HW, HWD, HWG])
    L = [r"\begin{tabular}{llcccccc}", r"\toprule",
         r"Backbone & Scoring & P & R & F1 & \multicolumn{3}{c}{Recall: spike / drift / schedule} \\",
         r"\midrule"]
    for bb, rows in [("PatchTST", [(PTG, "global"), (PTD, "HoD"), (PT, "HoW")]),
                     ("HOW profile", [(HWG, "global"), (HWD, "HoD"), (HW, "HoW")])]:
        for m, s in rows:
            g = ps[ps["model"] == m]
            rec = " & ".join(f"{tr.loc[(m, t), 'mean']:.2f}" for t in TYPES)
            L.append(f"{bb} & {s} & {ms(g['precision'])} & {ms(g['recall'])} & {ms(g['f1'], 3)} & {rec} \\\\")
        if bb == "PatchTST":
            L.append(r"\midrule")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("r7_granularity.tex", L)
    for m, key in [(PT, "PT"), (PTD, "PTD"), (PTG, "PTG"), (HW, "HW"), (HWD, "HWD"), (HWG, "HWG")]:
        for t in TYPES:
            M(f"{key}Rec{t.capitalize()}", float(tr.loc[(m, t), "mean"]))


def t_typesev(evd, orc, inj):
    d = evd[evd["model"].isin([PT, HW])].copy()
    d["delay_frac"] = d["delay_h"] / d["duration_h"]
    o = orc[orc["model"].isin([PT, HW])].copy()
    o["abs_err"] = (o["clip_kwh"] - o["true_kwh"]).abs() / o["true_kwh"]
    L = [r"\begin{tabular}{llrrcccccc}", r"\toprule",
         r" & & & & \multicolumn{2}{c}{Recall} & \multicolumn{2}{c}{Range recall} & Delay, ours & Oracle $|$err$|$ \\",
         r"\cmidrule(lr){5-6}\cmidrule(lr){7-8}",
         r"Type & Severity & $n$ & dur.\ (h) & ours & HOW & ours & HOW & h (frac.) & ours / HOW \\",
         r"\midrule"]
    for t in TYPES:
        for s in (1, 2, 3):
            a = d[(d["model"] == PT) & (d["type"] == t) & (d["severity"] == s)]
            b = d[(d["model"] == HW) & (d["type"] == t) & (d["severity"] == s)]
            oa = o[(o["model"] == PT) & (o["type"] == t) & (o["severity"] == s)]["abs_err"]
            ob = o[(o["model"] == HW) & (o["type"] == t) & (o["severity"] == s)]["abs_err"]
            if not len(a):
                L.append(f"{t} & {SEVN[s]} & 0 & --- & & & & & & \\\\")
                continue
            dl = a.loc[a["detected"], "delay_h"]
            fr = a.loc[a["detected"], "delay_frac"]
            dtxt = f"{dl.median():.0f} ({fr.median():.2f})" if len(dl) else "---"
            L.append(f"{t} & {SEVN[s]} & {len(a)} & {a['duration_h'].median():.0f} & "
                     f"{a['detected'].mean():.2f} & {b['detected'].mean():.2f} & "
                     f"{a['range_cov'].mean():.2f} & {b['range_cov'].mean():.2f} & {dtxt} & "
                     f"{oa.median():.2f} / {ob.median():.2f} \\\\")
        L.append(r"\midrule" if t != "schedule" else "")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("r7_typesev.tex", L)
    pt = d[d["model"] == PT]
    for t in TYPES:
        a = pt[pt["type"] == t]
        M(f"N{t.capitalize()}", int(len(a)))
        M(f"DelayMed{t.capitalize()}", float(a.loc[a["detected"], "delay_h"].median()))
        M(f"DelayFrac{t.capitalize()}", float(a.loc[a["detected"], "delay_frac"].median()))
        M(f"Dur{t.capitalize()}", float(a["duration_h"].median()))
    M("NEventsTotal", int(len(pt)))
    M("NScheduleSubtle", int(len(pt[(pt["type"] == "schedule") & (pt["severity"] == 1)])))
    # injection realism (SM)
    if inj is not None:
        g = inj.groupby(["type", "severity"])
        L = [r"\begin{tabular}{llrrrrrr}", r"\toprule",
             r"Type & Severity & $n$ & dur.\ (h) & mean add / resid.\ sd & peak add / resid.\ sd & mean add / median load & excess / test energy \\",
             r"\midrule"]
        for (t, s), x in g:
            L.append(f"{t} & {SEVN[s]} & {len(x)} & {x['duration_h'].median():.0f} & "
                     f"{x['mean_add_over_resid_sd'].median():.2f} & {x['peak_add_over_resid_sd'].median():.2f} & "
                     f"{100 * x['mean_add_over_median_load'].median():.1f}\\% & "
                     f"{100 * x['excess_over_test_energy'].median():.2f}\\% \\\\")
        L += [r"\bottomrule", r"\end{tabular}"]
        write("r7_injection.tex", L)
        sch = inj[inj["type"] == "schedule"]
        M("SchedAddSdMed", float(sch["mean_add_over_resid_sd"].median()))
        M("SchedExcessPctMax", float(100 * sch.groupby("severity")["excess_over_test_energy"].median().max()))
        sp = inj[inj["type"] == "spike"]
        M("SpikeAddSdMed", float(sp["mean_add_over_resid_sd"].median()))
        dr = inj[inj["type"] == "drift"]
        M("DriftAddSdMed", float(dr["mean_add_over_resid_sd"].median()))


def t_transfer(det):
    models = [PT, PTG, HW, HWG, TW, SL] + GEN
    rng = np.random.default_rng(7)
    L = [r"\begin{tabular}{lcc}", r"\toprule",
         r"Detector & Seen offices ($n$=24) & Unseen types ($n$=17) \\", r"\midrule"]
    bl = det.groupby(["model", "building_id", "seen"])["f1"].mean().reset_index()
    for m in models:
        cells = []
        for seen in (True, False):
            x = bl[(bl["model"] == m) & (bl["seen"] == seen)]["f1"].dropna().to_numpy()
            bs = [x[rng.integers(0, len(x), len(x))].mean() for _ in range(4000)]
            cells.append(f"{x.mean():.2f} [{np.percentile(bs, 2.5):.2f}, {np.percentile(bs, 97.5):.2f}]")
        L.append(f"{NICE[m]} & {cells[0]} & {cells[1]} \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("r7_transfer.tex", L)
    for m, key in [(PT, "PT"), (HW, "HW")]:
        for seen, s in [(True, "Seen"), (False, "Unseen")]:
            M(f"{key}F{s}", float(bl[(bl["model"] == m) & (bl["seen"] == seen)]["f1"].mean()))
    # buildings where ours < best generic baseline
    piv = bl.pivot_table(index="building_id", columns="model", values="f1")
    best_gen = piv[GEN].max(axis=1)
    M("NBldgDecline", int((piv[PT] < best_gen).sum()))
    M("NBldgDeclineHOW", int((piv[PT] < piv[HW]).sum()))


# ------------------------------------------------------------- waste
def t_waste(orc, lev, ops, ext, wci, sel):
    WM = [PT, HW, TW, PM]
    o = orc.copy()
    o["abs_err"] = (o["clip_kwh"] - o["true_kwh"]).abs() / o["true_kwh"]
    g = o.groupby("model").agg(true=("true_kwh", "sum"), clip=("clip_kwh", "sum"),
                               signed=("signed_kwh", "sum"), floor=("floor_kwh", "sum"),
                               med=("abs_err", "median"))
    L = [r"\begin{tabular}{lcccc}", r"\toprule",
         r"Counterfactual & signed & clip & floor-corrected & per-event median $|$err$|$ \\", r"\midrule"]
    for m in WM:
        if m not in g.index:
            continue
        r = g.loc[m]
        b = lambda c: pct((r[c] - r["true"]) / r["true"])
        L.append(f"{NICE[m]} & {b('signed')} & {b('clip')} & {b('floor')} & {r['med']:.2f} \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("r7_waste_oracle.tex", L)
    for m, key in [(PT, "PT"), (HW, "HW"), (TW, "TW"), (PM, "PM")]:
        r = g.loc[m]
        for c, suf in [("signed", "Signed"), ("clip", "Clip"), ("floor", "Floor")]:
            M(f"Orc{suf}{key}", float((r[c] - r["true"]) / r["true"]))
        M(f"OrcMed{key}", float(r["med"]))

    # level bias
    cols = [("patchtst_fullmask_mean", "PatchTST, full-window mask (canonical)"),
            ("patchtst_targetmask_mean", "PatchTST, target-hour-only mask at inference"),
            ("patchtst_patchmasktrain_mean", "PatchTST, 40\\% patch-mask training"),
            ("how_mean", "HOW profile")]
    L = [r"\begin{tabular}{lcccccc}", r"\toprule",
         r" & \multicolumn{2}{c}{all events} & \multicolumn{4}{c}{event-simple mean by type, and schedule kWh-weighted} \\",
         r"\cmidrule(lr){2-3}\cmidrule(lr){4-7}",
         r"Residual & simple & kWh-wt. & spike & drift & schedule & schedule (kWh-wt.) \\", r"\midrule"]
    for c, lab in cols:
        s = lev[c].mean(); w = np.average(lev[c], weights=lev["true_kwh"])
        per = [lev[lev["type"] == t][c].mean() for t in TYPES]
        sc = lev[lev["type"] == "schedule"]
        sw = np.average(sc[c], weights=sc["true_kwh"])
        L.append(f"{lab} & {s:+.2f} & {w:+.2f} & {per[0]:+.2f} & {per[1]:+.2f} & {per[2]:+.2f} & {sw:+.2f} \\\\")
        key = {"patchtst_fullmask_mean": "Full", "patchtst_targetmask_mean": "Target",
               "patchtst_patchmasktrain_mean": "PM", "how_mean": "HOW"}[c]
        M(f"Lev{key}", float(s)); M(f"Lev{key}Kwh", float(w))
        for t, v in zip(TYPES, per):
            M(f"Lev{key}{t.capitalize()}", float(v))
        M(f"Lev{key}ScheduleKwh", float(sw))
    L += [r"\bottomrule", r"\end{tabular}"]
    write("r7_levelbias.tex", L)

    # operational (flagged hours) + extension, one table with CIs
    def ci(model, est, stat):
        r = wci[(wci["model"] == model) & (wci["estimator"] == est) & (wci["stat"] == stat)]
        return r.iloc[0] if len(r) else None

    L = [r"\begin{tabular}{llrrrrrr}", r"\toprule",
         r" & & \multicolumn{3}{c}{$10^6$ kWh} & agg.\ bias & per-bldg & median per- \\",
         r"\cmidrule(lr){3-5}",
         r"Counterfactual & Window & matched & false add & missed & [site 95\% CI] & gross & bldg $|$err$|$ \\", r"\midrule"]
    for m in [PT, HW, TW]:
        o_ = ops[ops["model"] == m]
        e_ = ext[(ext["model"] == m)]
        rows = [("flags", o_, "flagged-hours")]
        chosen_modes = e_[e_["chosen"]].groupby("seed")["mode"].first()
        rule = "/".join(sorted(set(chosen_modes)))
        rows.append((f"extended [{rule}]", e_[e_["chosen"]], "ext:chosen"))
        for lab, dd, est in rows:
            a = ci(m, est, "agg_bias"); pg = ci(m, est, "pb_gross_rel"); md = ci(m, est, "median_abs_rel_err")
            L.append(f"{SHORT[m] if lab == 'flags' else ''} & {lab} & "
                     f"{dd['matched_err_kwh'].sum() / 1e6:+.2f} & {dd['false_add_kwh'].sum() / 1e6:+.2f} & "
                     f"$-${dd['missed_kwh'].sum() / 1e6:.2f} & {pct(a['value'])} [{pct(a['cluster_lo'], 0)}, {pct(a['cluster_hi'], 0)}] & "
                     f"{100 * pg['value']:.0f}\\% & {md['value']:.2f} \\\\")
        if m != TW:
            L.append(r"\midrule")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("r7_waste_ops.tex", L)
    for m, key in [(PT, "PT"), (HW, "HW"), (TW, "TW"), (PM, "PM")]:
        for est, pre in [("flagged-hours", "Ops"), ("ext:chosen", "Ext")]:
            for stat, suf in [("agg_bias", "Bias"), ("agg_gross_rel", "Gross"),
                              ("pb_gross_rel", "PbGross"), ("median_abs_rel_err", "MedErr")]:
                r = ci(m, est, stat)
                if r is None:
                    continue
                M(f"{pre}{suf}{key}", float(r["value"]))
                M(f"{pre}{suf}{key}CLo", float(r["cluster_lo"]))
                M(f"{pre}{suf}{key}CHi", float(r["cluster_hi"]))
        o_ = ops[ops["model"] == m]
        if len(o_):
            for c, suf in [("matched_err_kwh", "Matched"), ("false_add_kwh", "FalseAdd"),
                           ("missed_kwh", "Missed")]:
                M(f"Ops{suf}{key}", float(o_[c].sum() / 1e6))
        e_ = ext[(ext["model"] == m) & ext["chosen"]]
        if len(e_):
            for c, suf in [("matched_err_kwh", "Matched"), ("false_add_kwh", "FalseAdd"),
                           ("missed_kwh", "Missed")]:
                M(f"Ext{suf}{key}", float(e_[c].sum() / 1e6))
            modes = e_.groupby("seed")["mode"].first()
            M(f"ExtRule{key}", "/".join(sorted(set(modes))))
            M(f"ExtRuleCount{key}", int(modes.value_counts().iloc[0]))
            M(f"ExtRuleMajor{key}", str(modes.value_counts().index[0]))

    # all candidate rules: validation objective + test results
    s = sel[sel["what"].str.startswith("extension:")].copy()
    s["model"] = s["what"].str.replace("extension:", "", regex=False)
    vobj = s.groupby(["model", "option"])["val_obj"].mean()
    nch = s[s["chosen"] == True].groupby(["model", "option"]).size()  # noqa: E712
    L = [r"\begin{tabular}{llcccccc}", r"\toprule",
         r" & & \multicolumn{2}{c}{Validation} & \multicolumn{4}{c}{Test} \\",
         r"\cmidrule(lr){3-4}\cmidrule(lr){5-8}",
         r"Counterfactual & Rule & median $|$err$|$ & chosen & median $|$err$|$ & agg.\ bias & agg.\ gross & per-bldg gross \\",
         r"\midrule"]
    for m in [PT, HW, TW]:
        for mode in ("none", "z6", "z12", "cusum"):
            r = {st: ci(m, f"ext:{mode}", st) for st in
                 ("median_abs_rel_err", "agg_bias", "agg_gross_rel", "pb_gross_rel")}
            L.append(f"{NICE[m] if mode == 'none' else ''} & {mode} & {vobj.get((m, mode), np.nan):.2f} & "
                     f"{int(nch.get((m, mode), 0))}/3 & {r['median_abs_rel_err']['value']:.2f} & "
                     f"{pct(r['agg_bias']['value'])} & {100 * r['agg_gross_rel']['value']:.0f}\\% & "
                     f"{100 * r['pb_gross_rel']['value']:.0f}\\% \\\\")
            mk = {"none": "None", "z6": "Zsix", "z12": "Ztwelve", "cusum": "Cusum"}[mode]
            kk = {PT: "PT", HW: "HW", TW: "TW"}[m]
            for st, suf in [("median_abs_rel_err", "MedErr"), ("agg_bias", "Bias"),
                            ("agg_gross_rel", "Gross"), ("pb_gross_rel", "PbGross")]:
                M(f"Ext{mk}{suf}{kk}", float(r[st]["value"]))
            M(f"Val{mk}MedErr{kk}", float(vobj.get((m, mode), np.nan)))
        if m != TW:
            L.append(r"\midrule")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("r7_extension.tex", L)


def t_masking(det, evd, lev, orc):
    ps = per_seed(det, ["f1", "range_f1", "false_alarm_rate"])
    tr = type_recall(evd, [PT, PM])
    o = orc.copy()
    o["abs_err"] = (o["clip_kwh"] - o["true_kwh"]).abs() / o["true_kwh"]
    L = [r"\begin{tabular}{lcccccc}", r"\toprule",
         r"Training mask (inference: full window) & event F1 & range F1 & NIAR (\%) & schedule recall & schedule resid.\ ($\sigma$) & oracle median $|$err$|$ \\",
         r"\midrule"]
    for m, col, lab in [(PT, "patchtst_fullmask_mean", "full load channel (canonical)"),
                        (PM, "patchtst_patchmasktrain_mean", "40\\% random load patches")]:
        g = ps[ps["model"] == m]
        sres = lev[lev["type"] == "schedule"][col].mean()
        L.append(f"{lab} & {ms(g['f1'], 3)} & {ms(g['range_f1'], 3)} & {ms(g['false_alarm_rate'], 2, pct=True)} & "
                 f"{tr.loc[(m, 'schedule'), 'mean']:.2f} & {sres:+.2f} & {o[o['model'] == m]['abs_err'].median():.2f} \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("r7_masking.tex", L)


# ------------------------------------------------------------- misc / SM
def misc(det, leak, evd, interp, tun, win, syn, synevd, inj_nat):
    caus = det[det["model"] == PT].groupby("building_id")["f1"].mean()
    trd = leak.groupby("building_id")["f1"].mean()
    c = caus.index.intersection(trd.index)
    M("LeakDeltaF", float((trd[c] - caus[c]).mean()))
    if interp is not None:
        M("InterpHoursMedian", float(interp.groupby("building_id").size().median()))
        M("InterpHoursMax", int(interp.groupby("building_id").size().max()))
        M("InterpShareMax", float(interp.groupby("building_id").size().max() / 8784))
    real = load("injection_realism.csv")
    if real is not None and "interp_hours" in real:
        M("InterpEventShare", float((real["interp_hours"] > 0).mean()))
        M("InterpEventHoursShare", float(real["interp_hours"].sum() / real["duration_h"].sum()))
    lead = load("lead_label_durations.csv")  # LEAD 1.0-small labels (unchanged corpus)
    if lead is not None:
        M("LeadLabels", int(len(lead)))
        M("LeadMedianDur", float(lead["duration_h"].median()))
        M("LeadQninetyDur", float(lead["duration_h"].quantile(0.90)))
        M("LeadPctLeTwentyFour", float((lead["duration_h"] <= 24).mean()))
    if inj_nat is not None:
        M("NatShareGtThreeMed", float(inj_nat["share_abs_z_gt3"].median()))
        M("NatShareGtThreeMax", float(inj_nat["share_abs_z_gt3"].max()))
    if tun is not None:
        L = [r"\begin{tabular}{lllc}", r"\toprule", r"Detector & Seed & Selected configuration & validation event F1 \\", r"\midrule"]
        best = tun.loc[tun.groupby(["seed", "model"])["val_f1"].idxmax()]
        for _, r in best.sort_values(["model", "seed"]).iterrows():
            cfg = str(r["cfg"]).replace("_", r"\_").replace("{", "").replace("}", "").replace("'", "")
            L.append(f"{NICE.get(r['model'], r['model'])} & {r['seed']} & {cfg} & {r['val_f1']:.3f} \\\\")
        L += [r"\bottomrule", r"\end{tabular}"]
        write("r7_tuning.tex", L)
        M("NTuningConfigs", int(tun.groupby("seed").size().iloc[0]))
    if win is not None:
        ps = win.groupby(["model", "window_h", "seed"])[["f1", "false_alarm_rate"]].mean().reset_index()
        L = [r"\begin{tabular}{lccc}", r"\toprule", r"Detector & Trailing window & event F1 & NIAR (\%) \\", r"\midrule"]
        for m in [PT, HW]:
            for W in sorted(ps["window_h"].unique()):
                g = ps[(ps["model"] == m) & (ps["window_h"] == W)]
                L.append(f"{NICE[m] if W == 168 else ''} & {W} h{' (default)' if W == 336 else ''} & "
                         f"{ms(g['f1'], 3)} & {ms(g['false_alarm_rate'], 2, pct=True)} \\\\")
        L += [r"\bottomrule", r"\end{tabular}"]
        write("r7_window.tex", L)
        f = ps[ps["model"] == PT].groupby("window_h")["f1"].mean()
        M("WinFMin", float(f.min())); M("WinFMax", float(f.max()))
    if syn is not None:
        ps = syn.groupby(["model", "seed"])[["precision", "recall", "f1", "false_alarm_rate"]].mean().reset_index()
        tr = synevd.groupby(["model", "seed", "type"])["detected"].mean().groupby(["model", "type"]).mean()
        L = [r"\begin{tabular}{lccccc}", r"\toprule",
             r"Detector & P & R & F1 & NIAR (\%) & recall spike / drift / schedule \\", r"\midrule"]
        for gname, models in GROUPS[:4]:
            for m in models:
                g = ps[ps["model"] == m]
                if not len(g):
                    continue
                rec = " / ".join(f"{tr.get((m, t), np.nan):.2f}" for t in TYPES)
                L.append(f"{NICE[m]} & {ms(g['precision'])} & {ms(g['recall'])} & {ms(g['f1'], 3)} & "
                         f"{ms(g['false_alarm_rate'], 2, pct=True)} & {rec} \\\\")
        L += [r"\bottomrule", r"\end{tabular}"]
        write("r7_synthetic.tex", L)
        f = ps.groupby("model")["f1"].mean()
        for m, key in [(PT, "PT"), (HW, "HW"), (TW, "TW"), (PTD, "PTD"), (PTG, "PTG"), (HWG, "HWG")]:
            if m in f.index:
                M(f"Syn{key}F", float(f[m]))
        # severity matrix numbers for SM text
        sev = synevd[synevd["model"] == PT].groupby(["type", "severity"])["detected"].mean()
        M("SynPTSchedSubtle", float(sev.get(("schedule", 1), np.nan)))


def t_trainseed(ts, det):
    """Post-hoc: backbone effect (PatchTST - HOW, both HoW scoring) per training seed."""
    if ts is None:
        return
    rows = []
    canon = det[det["model"].isin([PT, HW])]
    cb = canon.pivot_table(index=["building_id"], columns="model", values="f1")
    rows.append(("coupled 123--125 (canonical)", cb[PT].mean(), (cb[PT] - cb[HW])))
    for t, g in ts.groupby("train_seed"):
        b = g.pivot_table(index="building_id", columns="model", values="f1")
        rows.append((f"{t}", b[PT].mean(), b[PT] - b[HW]))
    from scipy import stats as st
    L = [r"\begin{tabular}{lcccc}", r"\toprule",
         r"Training seed & PatchTST F1 & PatchTST $-$ HOW & 95\% CI & $p_t$ \\", r"\midrule"]
    diffs = []
    for lab, f, d in rows:
        d = d.dropna()
        q = st.t.ppf(0.975, len(d) - 1) * d.std(ddof=1) / np.sqrt(len(d))
        L.append(f"{lab} & {f:.3f} & {d.mean():+.3f} & [{d.mean() - q:+.3f}, {d.mean() + q:+.3f}] & "
                 f"{fmtp(st.ttest_1samp(d, 0).pvalue)} \\\\")
        diffs.append(d.mean())
    L += [r"\bottomrule", r"\end{tabular}"]
    write("r7_trainseed.tex", L)
    d7 = [r for r in rows if r[0].startswith("7")][0][2].dropna()
    M("TSSevenDiff", float(d7.mean()))
    M("TSSevenP", float(st.ttest_1samp(d7, 0).pvalue))
    M("TSDiffMin", float(min(diffs))); M("TSDiffMax", float(max(diffs)))
    M("TSN", int(ts["train_seed"].nunique()))
    ps_ = [st.ttest_1samp(r[2].dropna(), 0).pvalue for r in rows]
    M("TSPMin", float(min(ps_)))
    allf = [r[1] for r in rows]
    M("TSFMin", float(min(allf))); M("TSFMax", float(max(allf)))


def t_lead(ev, bydur):
    if ev is None:
        return
    M("LeadNBldg", int(len(ev)))
    M("LeadFlagOnLabel", float(ev["flagged_on_labeled"].sum() / ev["flagged_hours"].sum()))
    M("LeadRecovered", float(ev["flagged_on_labeled"].sum() / ev["labeled_hours"].sum()))
    M("LeadRunPrec", float(ev["run_precision"].mean()))
    M("LeadAlarmRate", float(ev["alarm_rate"].mean()))
    M("LeadLabelShare", float(ev["label_share_test"].mean()))
    g = bydur.groupby("bin", observed=True).agg(n=("detected", "size"), det=("detected", "mean"),
                                                cov=("covered", "mean"))
    L = [r"\begin{tabular}{lrcc}", r"\toprule",
         r"Labelled run length & runs & detected ($\geq$1 flagged hour) & flagged share of hours \\", r"\midrule"]
    for b, r in g.iterrows():
        L.append(f"{b} & {int(r['n'])} & {r['det']:.2f} & {r['cov']:.2f} \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("r7_lead.tex", L)
    M("LeadDetShort", float(g["det"].iloc[0]))
    M("LeadDetLong", float(g["det"].iloc[-1]))


def t_draws(dr):
    if dr is None:
        return
    g = dr.groupby(["type", "severity"]).agg(draws=("accepted", "size"), acc=("accepted", "sum"),
                                             overlap=("reason", lambda x: (x == "overlap").sum()),
                                             small=("reason", lambda x: (x == "peak<0.5kW").sum()))
    L = [r"\begin{tabular}{llrrrr}", r"\toprule",
         r"Type & Severity & draws & accepted & rejected: overlap & rejected: peak $<$0.5\,kW \\", r"\midrule"]
    for (t, sv), r in g.iterrows():
        L.append(f"{t} & {SEVN[sv]} & {int(r['draws'])} & {int(r['acc'])} & {int(r['overlap'])} & {int(r['small'])} \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("r7_draws.tex", L)
    sch = dr[(dr["type"] == "schedule") & (dr["severity"] == 1)]
    M("SchedSubtleDraws", int(len(sch)))
    M("SchedSubtleAccRate", float(sch["accepted"].mean()) if len(sch) else 0.0)
    M("SchedSubtleRejSmall", int((sch["reason"] == "peak<0.5kW").sum()))
    M("SchedSubtleRejOverlap", int((sch["reason"] == "overlap").sum()))
    M("DrawAccRate", float(dr["accepted"].mean()))
    # per-seed realized counts
    acc = dr[dr["accepted"]].groupby(["seed", "type"]).size().unstack(fill_value=0)
    L = [r"\begin{tabular}{l" + "r" * acc.shape[1] + "}", r"\toprule",
         "Seed & " + " & ".join(acc.columns) + r" \\", r"\midrule"]
    for sd_, r in acc.iterrows():
        L.append(f"{sd_} & " + " & ".join(str(int(v)) for v in r) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("r7_draws_seed.tex", L)


def check_consistency(fs):
    """2x2 cell means must reproduce the simple-effect estimates exactly."""
    c = fs[(fs["metric"] == "f1") & (fs["family"] == "cell")].set_index("contrast")["estimate"]
    se = fs[(fs["metric"] == "f1") & (fs["family"] == "simple")].set_index("contrast")["estimate"]
    assert abs((c[PT] - c[HW]) - se["PatchTST(HoW) - HOW(HoW)  [backbone | HoW]"]) < 1e-9
    assert abs((c[PT] - c[PTG]) - se["PatchTST(HoW) - PatchTST(global)  [scoring | PatchTST]"]) < 1e-9
    assert abs((c[HW] - c[HWG]) - se["HOW(HoW) - HOW(global)  [scoring | HOW]"]) < 1e-9
    print("factorial cells and contrasts consistent")


def t_schedsens(d):
    """H4: additive schedule injection + relative rejection (sensitivity)."""
    base = os.path.join(MC, "schedule_sens")
    if not os.path.exists(os.path.join(base, "factorial_stats.csv")):
        return
    det = pd.read_csv(os.path.join(base, "detection_metrics.csv"))
    evd = pd.read_csv(os.path.join(base, "event_detail.csv"))
    fs = pd.read_csv(os.path.join(base, "factorial_stats.csv"))
    inj = pd.read_csv(os.path.join(base, "injection.csv"))
    ps = det.groupby(["model", "seed"])[["f1", "range_f1", "false_alarm_rate"]].mean()
    tr = evd.groupby(["model", "seed", "type"])["detected"].mean().groupby(["model", "type"]).mean()
    rc = evd[evd["type"] == "schedule"].groupby("model")["range_cov"].mean()
    order = [PT, PTD, PTG, HW, HWD, HWG, TW]
    L = [r"\begin{tabular}{lccccc}", r"\toprule",
         r"Detector & event F1 & range F1 & recall spike / drift / schedule & schedule range recall & NIAR (\%) \\",
         r"\midrule"]
    for m in order:
        g = ps.loc[m]
        rec = " / ".join(f"{tr.get((m, t), np.nan):.2f}" for t in TYPES)
        L.append(f"{NICE[m]} & {ms(g['f1'], 3)} & {ms(g['range_f1'], 3)} & {rec} & {rc.get(m, np.nan):.2f} & "
                 f"{ms(g['false_alarm_rate'], 2, pct=True)} \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    write("r7_schedsens.tex", L)
    ev = fs[(fs["metric"] == "f1")]
    get = lambda c, col: float(ev[ev["contrast"] == c][col].iloc[0])
    for c, key in [("scoring main effect", "SCME"), ("backbone main effect", "BBME"),
                   ("interaction (scoring effect: PatchTST - HOW)", "INT"),
                   ("PatchTST(HoW) - HOW(HoW)  [backbone | HoW]", "BBHow")]:
        M(f"SS{key}", get(c, "estimate")); M(f"SS{key}P", get(c, "p_t"))
        M(f"SS{key}CLo", get(c, "cluster_lo")); M(f"SS{key}CHi", get(c, "cluster_hi"))
    t = ev[ev["family"] == "tost"].iloc[0]
    M("SSTOSTp", float(t["p_tost"]))
    for m, key in [(PT, "PT"), (PTD, "PTD"), (HW, "HW"), (HWD, "HWD"), (PTG, "PTG")]:
        M(f"SSRecSched{key}", float(tr.get((m, "schedule"), np.nan)))
        M(f"SSF{key}", float(ps.loc[m]["f1"].mean()))
    sch = inj[inj["type"] == "schedule"]
    M("SSSchedN", int(len(sch)))
    M("SSSchedSubtleN", int((sch["severity"] == 1).sum()))
    M("SSSchedAddSdMed", float(sch["mean_add_over_resid_sd"].median()))
    M("SSSchedExcessPctMed", float(100 * sch["excess_over_test_energy"].median()))


def write_numbers():
    out = ["%% AUTO-GENERATED by scripts/make_tables_r7.py from results/final_r7/*.csv. Do not edit."]
    for k, v in MACROS.items():
        assert k.isalpha(), k
        if isinstance(v, (float, np.floating)):
            out.append(f"\\newcommand{{\\{k}}}{{{v:.6f}}}" if abs(v) < 1e5 else f"\\newcommand{{\\{k}}}{{{v:.0f}}}")
        else:
            out.append(f"\\newcommand{{\\{k}}}{{{v}}}")
    open(NUM, "w").write("\n".join(out) + "\n")
    print(f"wrote {len(MACROS)} macros")


def main():
    det = load("detection_metrics.csv")
    evd = load("event_detail.csv")
    fs = load("factorial_stats.csv")
    orc, lev, ops = load("waste_oracle.csv"), load("levelbias.csv"), load("waste_ops.csv")
    ext, wci, sel = load("extension.csv"), load("waste_ci.csv"), load("selection_log.csv")
    t_detection(det)
    t_factorial(fs)
    t_granularity(det, evd)
    t_typesev(evd, orc, load("injection_realism.csv"))
    t_transfer(det)
    t_waste(orc, lev, ops, ext, wci, sel)
    t_masking(det, evd, lev, orc)
    misc(det, load("leakage.csv"), evd, load("interp_mask.csv"), load("tuning_log.csv"),
         load("window_sensitivity.csv"), load("synthetic_metrics.csv"),
         load("synthetic_event_detail.csv"), load("natural_excursions.csv"))
    t_trainseed(load("trainseed_sensitivity.csv"), det)
    t_lead(load("lead_eval.csv"), load("lead_by_duration.csv"))
    t_draws(load("injection_draws.csv"))
    check_consistency(fs)
    t_schedsens(None)
    write_numbers()


if __name__ == "__main__":
    main()
